application: wda-mobile
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico


- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /api/index
  script: index.py

- url: /api/.*
  script: api/api.py

- url: /admin/.*
  script: /admin/admin.py
  login: admin
    
- url: /search
  script: search.py

- url: /.*
  script: main.py
